apiVersion: v1
kind: Pod
metadata:
  annotations:
    adaptDeployID: movieapp-production
    adaptName: '["App","App-Group","UrlRouter","UrlRouter","UrlRouter","UrlRouter","UrlRouter","UrlRouter","UrlRouter","UrlRouter","UrlRouter-Group","UrlRouter","UrlRouter"]'
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"nginx-url-router"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"nginx-url-router"}]},"modified":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"adaptDeployID":"movieapp-production","adaptName":"[\"App\",\"App-Group\",\"UrlRouter\",\"UrlRouter\",\"UrlRouter\",\"UrlRouter\",\"UrlRouter\",\"UrlRouter\",\"UrlRouter\",\"UrlRouter\",\"UrlRouter-Group\",\"UrlRouter\",\"UrlRouter\"]"},"labels":{"adaptName":"urlrouter-5611b0b4e0bdd010294a3be6ca0888b5"},"name":"urlrouter-5611b0b4e0bdd010294a3be6ca0888b5","namespace":"default"},"spec":{"containers":[{"image":"gcr.io/devops3-analiza/nginx-url-router:atwhstdt","imagePullPolicy":"IfNotPresent","name":"nginx-url-router","ports":[{"containerPort":8080,"protocol":"TCP"}]}],"terminationGracePeriodSeconds":0}}
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2022-03-27T20:19:19Z"
  labels:
    adaptName: urlrouter-5611b0b4e0bdd010294a3be6ca0888b5
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:adaptDeployID: {}
          f:adaptName: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:adaptName: {}
      f:spec:
        f:containers:
          k:{"name":"nginx-url-router"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8080,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kubectl
    operation: Update
    time: "2022-03-27T20:19:19Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-scheduler
    operation: Update
    time: "2022-03-27T20:19:20Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.32.128.3"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2022-03-27T20:21:39Z"
  name: urlrouter-5611b0b4e0bdd010294a3be6ca0888b5
  namespace: default
  resourceVersion: "210379"
  uid: 292cf599-f87e-45f4-b20f-7a9f1749d15f
spec:
  containers:
  - image: gcr.io/devops3-analiza/nginx-url-router:atwhstdt
    imagePullPolicy: IfNotPresent
    name: nginx-url-router
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        ephemeral-storage: 1Gi
        memory: 2Gi
      requests:
        cpu: 500m
        ephemeral-storage: 1Gi
        memory: 2Gi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nvfr9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gk3-loai-production-clus-nap-ri32gh68-a913d007-b2xs
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: gke.io/optimize-utilization-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-nvfr9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-27T20:21:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-27T20:21:39Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-27T20:21:39Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-27T20:21:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d03e85be059225891ec4d68645a3c90b793714e2b447957e91c566ec25c8e3b8
    image: gcr.io/devops3-analiza/nginx-url-router:atwhstdt
    imageID: gcr.io/devops3-analiza/nginx-url-router@sha256:72b820de1f50cce6bfe1f010ab17eeb4d6032490a7c711750079dfafc2ff7b67
    lastState: {}
    name: nginx-url-router
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-03-27T20:21:38Z"
  hostIP: 10.132.0.4
  phase: Running
  podIP: 10.32.128.3
  podIPs:
  - ip: 10.32.128.3
  qosClass: Guaranteed
  startTime: "2022-03-27T20:21:19Z"
