steps:
### Deployment by adapt
  - id: 'pre-deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
          npm install -g @adpt/cli
          gcloud container clusters get-credentials loai-production-cluster --zone europe-west1
          gcloud auth configure-docker --quiet
          export MYPROJECTID=devops3-analiza
          export KUBE_DOCKER_REPO=gcr.io/${MYPROJECTID}/movie_db_production
          

# Run Adapt
  - id: 'deploy'
    name: 'gcr.io/devops3-analiza/movie_db_production'
    entrypoint: 'adapt' 
    env: 
    - 'KUBECONFIG=gcr.io/devops3-analiza/movie_db_production'
    - 'KUBE_DOCKER_REPO=gcr.io/devops3-analiza/movie_db_production'
    # args: ['run','k8s-test','--deployID','movieapp-production']
    args: ['update','movieapp-production']
    dir: 'deploy'
             
## Timeout
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY