steps:
### Deployment by adapt
  - id: 'pre-deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
          gcloud container clusters get-credentials loai-production-cluster --region europe-west1
          gcloud auth configure-docker --quiet
          export KUBE_DOCKER_REPO=gcr.io/devops3-analiza 

# Run Adapt
  - id: 'deploy'
    name: 'gcr.io/devops3-analiza'
    entrypoint: 'adapt' 
    env: 
    - 'KUBECONFIG=gcr.io/devops3-analiza'
    - 'KUBE_DOCKER_REPO=gcr.io/devops3-analiza'
    # args: ['run','k8s-test','--deployID','movieapp-production']
    args: ['update','movieapp-production']
    dir: 'deploy'
             
### Timeout
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY